/**
 * Rich mock data for Ad Manager UI development.
 * Used when backend is not yet returning real campaign data.
 */

import type { AdCampaign, AdAccount, DashboardMetrics, DailyMetricPoint } from '../types/ads';

// ─── Mock Ad Accounts ─────────────────────────────────────────────────────────

export const MOCK_AD_ACCOUNTS: AdAccount[] = [
  {
    id: 'acc_google_1',
    workspaceId: 'ws_1',
    platform: 'GOOGLE',
    externalAccountId: '123-456-7890',
    accountName: 'Stone Media LLC',
    status: 'ACTIVE',
    connectedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    connectedByUserId: 'user_1',
    lastSyncAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    tokenExpiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    disconnectedAt: null,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc_fb_1',
    workspaceId: 'ws_1',
    platform: 'FACEBOOK',
    externalAccountId: 'act_987654321',
    accountName: 'Stone Media Facebook',
    status: 'ACTIVE',
    connectedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    connectedByUserId: 'user_1',
    lastSyncAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    tokenExpiresAt: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    disconnectedAt: null,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ─── Mock Campaigns ───────────────────────────────────────────────────────────

export const MOCK_CAMPAIGNS: (AdCampaign & {
  reach30d: number;
  impressions30d: number;
  clicks30d: number;
  frequency30d: number;
})[] = [
  {
    id: 'camp_001',
    workspaceId: 'ws_1',
    adAccountId: 'acc_fb_1',
    platform: 'FACEBOOK',
    adType: 'FACEBOOK_LEAD',
    name: 'Q2 Lead Gen — Homeowners Florida',
    objective: 'LEAD_GENERATION',
    status: 'ACTIVE',
    rejectionReason: null,
    budgetType: 'DAILY',
    budgetAmountCents: 5000,
    scheduleType: 'CONTINUOUS',
    startDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    bidStrategy: null,
    targetCpaCents: null,
    targeting: { locations: ['Tampa, FL', 'Orlando, FL', 'Miami, FL'], ageMin: 28, ageMax: 65, genders: ['MALE', 'FEMALE'] },
    creative: { headlines: ['Get a Free Home Estimate'], descriptions: ['No obligation quote in 24 hours'], callToAction: 'Get Quote', imageUrls: [] },
    platformCampaignId: 'fb_23849123',
    cachedSpend30dCents: 124580,
    cachedLeads30d: 87,
    cachedCtr30d: 0.0312,
    metricsCachedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    createdByUserId: 'user_1',
    lastEditedByUserId: 'user_1',
    launchedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    reach30d: 42300,
    impressions30d: 58100,
    clicks30d: 1814,
    frequency30d: 1.37,
  },
  {
    id: 'camp_002',
    workspaceId: 'ws_1',
    adAccountId: 'acc_google_1',
    platform: 'GOOGLE',
    adType: 'GOOGLE_SEARCH',
    name: 'Brand — [Exact] Stone AIO Keywords',
    objective: 'Leads',
    status: 'ACTIVE',
    rejectionReason: null,
    budgetType: 'DAILY',
    budgetAmountCents: 8000,
    scheduleType: 'CONTINUOUS',
    startDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    bidStrategy: 'MAXIMIZE_CONVERSIONS',
    targetCpaCents: null,
    targeting: {
      locations: ['United States'],
      keywords: [
        { text: 'stone aio', matchType: 'EXACT' },
        { text: 'ai marketing platform', matchType: 'PHRASE' },
        { text: 'crm automation software', matchType: 'BROAD' },
      ],
    },
    creative: { headlines: ['Stone AIO — AI Marketing', 'CRM + Ads in One Platform', 'Start Free Today'], descriptions: ['Automate your entire marketing stack with AI.', 'Google + Meta ads, CRM, and workflows in one place.'], callToAction: 'Sign Up Free', finalUrl: 'https://stoneaio.com' },
    platformCampaignId: 'g_9182736450',
    cachedSpend30dCents: 198200,
    cachedLeads30d: 143,
    cachedCtr30d: 0.0847,
    metricsCachedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    createdByUserId: 'user_1',
    lastEditedByUserId: 'user_1',
    launchedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 46 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    reach30d: 0,
    impressions30d: 12450,
    clicks30d: 1054,
    frequency30d: 0,
  },
  {
    id: 'camp_003',
    workspaceId: 'ws_1',
    adAccountId: 'acc_fb_1',
    platform: 'FACEBOOK',
    adType: 'FACEBOOK_FEED',
    name: 'Retargeting — Website Visitors 30d',
    objective: 'TRAFFIC',
    status: 'ACTIVE',
    rejectionReason: null,
    budgetType: 'DAILY',
    budgetAmountCents: 2500,
    scheduleType: 'CONTINUOUS',
    startDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    bidStrategy: null,
    targetCpaCents: null,
    targeting: { locations: ['United States'], ageMin: 25, ageMax: 55 },
    creative: { headlines: ['Still Thinking It Over?'], descriptions: ['You looked — now let us show you what Stone AIO can do for your business.'], callToAction: 'Learn More', imageUrls: [] },
    platformCampaignId: 'fb_55001122',
    cachedSpend30dCents: 42100,
    cachedLeads30d: 18,
    cachedCtr30d: 0.0189,
    metricsCachedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    createdByUserId: 'user_1',
    lastEditedByUserId: 'user_1',
    launchedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    reach30d: 18900,
    impressions30d: 31600,
    clicks30d: 597,
    frequency30d: 1.67,
  },
  {
    id: 'camp_004',
    workspaceId: 'ws_1',
    adAccountId: 'acc_google_1',
    platform: 'GOOGLE',
    adType: 'GOOGLE_SEARCH',
    name: 'Competitor — Conquest Keywords',
    objective: 'Leads',
    status: 'PAUSED',
    rejectionReason: null,
    budgetType: 'DAILY',
    budgetAmountCents: 3500,
    scheduleType: 'CONTINUOUS',
    startDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    bidStrategy: 'MAXIMIZE_CLICKS',
    targetCpaCents: null,
    targeting: {
      locations: ['United States'],
      keywords: [
        { text: 'go high level alternative', matchType: 'PHRASE' },
        { text: 'hubspot alternative small business', matchType: 'PHRASE' },
      ],
    },
    creative: { headlines: ['Better Than HubSpot?', 'Switch to Stone AIO Today'], descriptions: ['All-in-one platform at a fraction of the cost.'], callToAction: 'Compare Now', finalUrl: 'https://stoneaio.com/compare' },
    platformCampaignId: 'g_7654321890',
    cachedSpend30dCents: 87300,
    cachedLeads30d: 54,
    cachedCtr30d: 0.0521,
    metricsCachedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    createdByUserId: 'user_1',
    lastEditedByUserId: 'user_1',
    launchedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 61 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    reach30d: 0,
    impressions30d: 6820,
    clicks30d: 355,
    frequency30d: 0,
  },
  {
    id: 'camp_005',
    workspaceId: 'ws_1',
    adAccountId: 'acc_fb_1',
    platform: 'FACEBOOK',
    adType: 'FACEBOOK_LEAD',
    name: 'Roofing Leads — Texas + Oklahoma',
    objective: 'LEAD_GENERATION',
    status: 'ACTIVE',
    rejectionReason: null,
    budgetType: 'DAILY',
    budgetAmountCents: 6500,
    scheduleType: 'CONTINUOUS',
    startDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    bidStrategy: null,
    targetCpaCents: null,
    targeting: { locations: ['Houston, TX', 'Dallas, TX', 'Oklahoma City, OK'], ageMin: 30, ageMax: 65 },
    creative: { headlines: ['Free Roof Inspection'], descriptions: ['Storm damage? Get a free inspection today.'], callToAction: 'Book Now', imageUrls: [] },
    platformCampaignId: 'fb_77889900',
    cachedSpend30dCents: 38400,
    cachedLeads30d: 62,
    cachedCtr30d: 0.0428,
    metricsCachedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    createdByUserId: 'user_1',
    lastEditedByUserId: 'user_1',
    launchedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    reach30d: 28700,
    impressions30d: 41200,
    clicks30d: 1764,
    frequency30d: 1.44,
  },
  {
    id: 'camp_006',
    workspaceId: 'ws_1',
    adAccountId: 'acc_google_1',
    platform: 'GOOGLE',
    adType: 'GOOGLE_DISPLAY',
    name: 'Awareness — Display Network Q2',
    objective: 'Awareness',
    status: 'DRAFT',
    rejectionReason: null,
    budgetType: 'DAILY',
    budgetAmountCents: 4000,
    scheduleType: 'SCHEDULED',
    startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
    bidStrategy: 'MAXIMIZE_CLICKS',
    targetCpaCents: null,
    targeting: { locations: ['United States'] },
    creative: { headlines: ['Stone AIO — AI Platform'], descriptions: ['Discover the all-in-one platform powering modern agencies.'], callToAction: 'Learn More', imageUrls: [] },
    platformCampaignId: null,
    cachedSpend30dCents: 0,
    cachedLeads30d: 0,
    cachedCtr30d: 0,
    metricsCachedAt: null,
    createdByUserId: 'user_1',
    lastEditedByUserId: 'user_1',
    launchedAt: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    reach30d: 0,
    impressions30d: 0,
    clicks30d: 0,
    frequency30d: 0,
  },
  {
    id: 'camp_007',
    workspaceId: 'ws_1',
    adAccountId: 'acc_fb_1',
    platform: 'FACEBOOK',
    adType: 'FACEBOOK_FEED',
    name: 'Spring Sale — 40% Off Annual Plan',
    objective: 'TRAFFIC',
    status: 'ENDED',
    rejectionReason: null,
    budgetType: 'LIFETIME',
    budgetAmountCents: 150000,
    scheduleType: 'SCHEDULED',
    startDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    bidStrategy: null,
    targetCpaCents: null,
    targeting: { locations: ['United States', 'Canada'], ageMin: 22, ageMax: 55 },
    creative: { headlines: ['Spring Sale Ends Soon', '40% Off Annual Plans'], descriptions: ['Limited time. Lock in your rate today.'], callToAction: 'Shop Now', imageUrls: [] },
    platformCampaignId: 'fb_11223344',
    cachedSpend30dCents: 149800,
    cachedLeads30d: 211,
    cachedCtr30d: 0.0234,
    metricsCachedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    createdByUserId: 'user_1',
    lastEditedByUserId: 'user_1',
    launchedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 92 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    reach30d: 68400,
    impressions30d: 98700,
    clicks30d: 2311,
    frequency30d: 1.44,
  },
];

// ─── Mock Dashboard Metrics ───────────────────────────────────────────────────

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  totalSpendCents: 490580,
  totalLeads: 364,
  costPerLeadCents: 1348,
  activeCampaigns: 4,
  spendDeltaPct: 12.4,
  leadsDeltaPct: 18.7,
};

// ─── Mock Chart Data (last 30 days) ──────────────────────────────────────────

export const MOCK_CHART_DATA: DailyMetricPoint[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  const base = 0.5 + Math.sin(i / 5) * 0.3 + Math.random() * 0.2;
  return {
    date: date.toISOString().slice(0, 10),
    googleSpendCents: Math.round(3000 + base * 5000 + Math.random() * 2000),
    facebookSpendCents: Math.round(2000 + base * 3500 + Math.random() * 1500),
    googleLeads: Math.round(2 + base * 6 + Math.random() * 3),
    facebookLeads: Math.round(1 + base * 5 + Math.random() * 4),
  };
});
